# Generated by Django 4.0 on 2021-12-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='title',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
