# Generated by Django 4.0 on 2021-12-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_feedback_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_surname',
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
